// Power Query (M) — connect Power BI to the portfolio data over the web.
//
// HOW TO USE
//   Power BI Desktop -> Home -> Get data -> Blank query -> Advanced Editor
//   Paste ONE query below, click Done, rename the query, repeat for the others.
//   These pull straight from the repo's raw GitHub URLs, so they always reflect
//   the latest committed data (regenerated by scripts/run_all.py).
//
// Source data: Australian open data (ABS, Dept of Finance, Commonwealth Grants
// Commission). See ../CONNECT.md and ../sql/analysis.sql.

// ---- Query: BusinessChurn -------------------------------------------------
let
    Source = Csv.Document(
        Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/business_churn_by_state.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"state", type text}, {"businesses", Int64.Type}, {"share_pct", type number}})
in
    Typed

// ---- Query: AdSpend -------------------------------------------------------
let
    Source = Csv.Document(
        Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/govt_ad_spend_by_channel.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"channel", type text}, {"spend_m", type number}, {"share_pct", type number}})
in
    Typed

// ---- Query: RetailDemand --------------------------------------------------
let
    Source = Csv.Document(
        Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/retail_demand_series.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"period", type text}, {"turnover_m", type number}}),
    WithDate = Table.AddColumn(Typed, "date",
        each Date.FromText([period] & "-01"), type date)
in
    WithDate

// ---- Query: GstDistribution -----------------------------------------------
let
    Source = Csv.Document(
        Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/gst_reconciliation_by_state.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"state", type text}, {"gst_bn", type number}, {"share_pct", type number}})
in
    Typed
