table AdSpend
	lineageTag: 7faf4ab2-dc98-408e-aa54-df8a31058a4e

	measure 'Total Ad Spend ($M)' = SUM ( AdSpend[spend_m] )
		formatString: $#,##0.0
		displayFolder: Ad spend
		lineageTag: faf737b3-8772-4bc1-9b38-2d901202dd25

	measure 'Digital Share %' = DIVIDE ( CALCULATE ( SUM ( AdSpend[spend_m] ), AdSpend[channel] = "Digital" ), SUM ( AdSpend[spend_m] ) )
		formatString: 0.0%
		displayFolder: Ad spend
		lineageTag: 3fe286c9-2b7c-4fcf-b54e-0d002903fbe5

	column channel
		dataType: string
		isNullable: false
		lineageTag: ca6f45cd-6d55-4459-bfc8-47e763cb741e
		sourceColumn: channel

	column spend_m
		dataType: double
		isNullable: false
		lineageTag: bca938a2-3b20-419f-aa12-d487e18e3a49
		sourceColumn: spend_m

	column share_pct
		dataType: double
		isNullable: false
		lineageTag: 280cebe6-3f49-4e43-a117-e5a266390405
		sourceColumn: share_pct

	partition AdSpend = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/govt_ad_spend_by_channel.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"channel", type text}, {"spend_m", type number}, {"share_pct", type number}}) in Typed

