table BusinessChurn
	lineageTag: 5bf7d645-3c10-431b-aa7a-7f15581525df

	measure 'Total Businesses' = SUM ( BusinessChurn[businesses] )
		formatString: #,##0
		displayFolder: Business Churn
		lineageTag: 1fb21021-90da-4e64-8cf9-75fce4e83ee0

	measure 'Top State Share %' = MAXX ( BusinessChurn, BusinessChurn[share_pct] )
		formatString: 0.0"%"
		displayFolder: Business Churn
		lineageTag: ba80a78e-31a6-4761-9fe9-c2c2a982f34b

	measure 'State Count' = DISTINCTCOUNT ( BusinessChurn[state] )
		formatString: #,##0
		displayFolder: Business Churn
		lineageTag: 92dc970d-7997-4625-a6a3-44f3ecfaef3d

	column state
		dataType: string
		isNullable: false
		lineageTag: 8b8207a7-5d2f-4501-b17e-c69370e7429c
		sourceColumn: state

	column businesses
		dataType: int64
		isNullable: false
		lineageTag: 5b398cff-4a10-4d70-b8e8-275f92a6b378
		sourceColumn: businesses

	column share_pct
		dataType: double
		isNullable: false
		lineageTag: 1b321102-809b-4eb8-837b-d9531fc4ad8c
		sourceColumn: share_pct

	partition BusinessChurn = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/business_churn_by_state.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"state", type text}, {"businesses", Int64.Type}, {"share_pct", type number}}) in Typed

