table BusinessChurn
	lineageTag: 0a365675-8f4a-4023-b2b7-f51d4e0d7ae2

	measure 'Total Businesses' = SUM ( BusinessChurn[businesses] )
		formatString: #,##0
		displayFolder: Business churn
		lineageTag: c4e0fb1a-465b-4ba0-ba87-f2d6d852dfbe

	measure 'Top State Share %' = MAX ( BusinessChurn[share_pct] )
		formatString: 0.0\%
		displayFolder: Business churn
		lineageTag: 80e375f7-5507-48c7-bcfa-97cf4a949867

	column state
		dataType: string
		isNullable: false
		lineageTag: d5981f3e-3dfd-461e-a572-305795071852
		sourceColumn: state

	column businesses
		dataType: int64
		isNullable: false
		lineageTag: 3521737c-2197-4832-8347-f6589f3d6559
		sourceColumn: businesses

	column share_pct
		dataType: double
		isNullable: false
		lineageTag: cc80ce5a-ee49-4a87-bf99-fa327febf73b
		sourceColumn: share_pct

	partition BusinessChurn = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/business_churn_by_state.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"state", type text}, {"businesses", Int64.Type}, {"share_pct", type number}}) in Typed

