table GstDistribution
	lineageTag: da70f76e-a3df-4855-a694-160e5af37414

	measure 'GST Pool ($bn)' = SUM ( GstDistribution[gst_bn] )
		formatString: $#,##0.0
		displayFolder: GST Distribution
		lineageTag: 19332db3-6875-45fb-9936-9d0c11c47e83

	measure 'Largest Recipient' = CALCULATE ( MAX ( GstDistribution[state] ), TOPN ( 1, GstDistribution, GstDistribution[gst_bn], DESC ) )
		displayFolder: GST Distribution
		lineageTag: 4daf517d-29c8-4237-b365-fa63da3c48f9

	measure 'Largest Recipient Share %' = MAXX ( GstDistribution, GstDistribution[share_pct] )
		formatString: 0.0"%"
		displayFolder: GST Distribution
		lineageTag: 5650611e-40a1-423a-b447-7bbd44c6d963

	column state
		dataType: string
		isNullable: false
		lineageTag: 4de07119-e954-4480-84cd-b354a4f42e3c
		sourceColumn: state

	column gst_bn
		dataType: double
		isNullable: false
		lineageTag: 5459d21b-038c-412d-a8f6-e071df72368e
		sourceColumn: gst_bn

	column share_pct
		dataType: double
		isNullable: false
		lineageTag: 8cfb4657-62e4-4d0f-ad29-2e163c2d2d3f
		sourceColumn: share_pct

	partition GstDistribution = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/gst_reconciliation_by_state.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"state", type text}, {"gst_bn", type number}, {"share_pct", type number}}) in Typed

