table GstDistribution
	lineageTag: bc8565de-a437-4e39-9148-1e5a13ca29bb

	measure 'GST Pool ($bn)' = SUM ( GstDistribution[gst_bn] )
		formatString: $#,##0.0
		displayFolder: GST
		lineageTag: d6a31c71-8cee-4e26-afc5-30adeabda9ea

	measure 'Largest Recipient' = MAXX ( TOPN ( 1, GstDistribution, GstDistribution[gst_bn], DESC ), GstDistribution[state] )
		displayFolder: GST
		lineageTag: 57b70921-8c0a-4085-af0b-d9397fd52d7b

	column state
		dataType: string
		isNullable: false
		lineageTag: 9aeadb21-fe2e-4247-b14a-ceeb54cf93d0
		sourceColumn: state

	column gst_bn
		dataType: double
		isNullable: false
		lineageTag: d3b98479-0728-4d85-8188-bda56b393f0e
		sourceColumn: gst_bn

	column share_pct
		dataType: double
		isNullable: false
		lineageTag: 90460061-062b-49ad-8dbb-7d7c6187e7fe
		sourceColumn: share_pct

	/// Rolls SA, TAS, ACT and NT up to 'Other (SA/TAS/ACT/NT)' so GST joins the conformed State dimension at a matching grain.
	column StateGroup = IF ( GstDistribution[state] IN { "NSW", "VIC", "QLD", "WA" }, GstDistribution[state], "Other (SA/TAS/ACT/NT)" )
		dataType: string
		lineageTag: cc35fe29-0d74-47d9-a1f1-ffa7371209c2

	partition GstDistribution = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/gst_reconciliation_by_state.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"state", type text}, {"gst_bn", type number}, {"share_pct", type number}}) in Typed

