table RetailDemand
	lineageTag: 979a3255-3dfb-40a2-a19e-ff9f1791d9ca

	measure 'Latest Turnover ($M)' = MAXX ( TOPN ( 1, RetailDemand, RetailDemand[period], DESC ), RetailDemand[turnover_m] )
		formatString: $#,##0.0
		displayFolder: Retail
		lineageTag: 7ed2c2dc-dce2-43b5-b479-8d31a3ba675b

	measure 'Turnover Growth %' = VAR L = MAXX ( TOPN ( 1, RetailDemand, RetailDemand[period], DESC ), RetailDemand[turnover_m] ) VAR F = MAXX ( TOPN ( 1, RetailDemand, RetailDemand[period], ASC ), RetailDemand[turnover_m] ) RETURN DIVIDE ( L - F, F )
		formatString: 0.0%
		displayFolder: Retail
		lineageTag: e9b135fc-53de-4579-bda2-6318addc83f5

	column period
		dataType: string
		isNullable: false
		lineageTag: 4ea6a9ab-8bf1-4cef-9a82-4f22217770ac
		sourceColumn: period

	column turnover_m
		dataType: double
		isNullable: false
		lineageTag: 308e4b05-156f-4a64-bdd9-a971f2633b18
		sourceColumn: turnover_m

	column date
		dataType: dateTime
		isNullable: false
		lineageTag: e97cb51c-fd5f-428e-add7-9de94747fa59
		sourceColumn: date

	partition RetailDemand = m
		mode: import
		source = let Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GauravWarke/Portfolio/main/data/retail_demand_series.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Typed = Table.TransformColumnTypes(Headers, {{"period", type text}, {"turnover_m", type number}}), WithDate = Table.AddColumn(Typed, "date", each Date.FromText([period] & "-01"), type date) in WithDate

